/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_AS_Context_v1130_H_
#define	_AS_Context_v1130_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AS-Context-v1130 */
typedef struct AS_Context_v1130 {
	OCTET_STRING_t	*idc_Indication_r11	/* OPTIONAL */;
	OCTET_STRING_t	*mbmsInterestIndication_r11	/* OPTIONAL */;
	OCTET_STRING_t	*powerPrefIndication_r11	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	OCTET_STRING_t	*sidelinkUEInformation_r12	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AS_Context_v1130_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AS_Context_v1130;

#ifdef __cplusplus
}
#endif

#endif	/* _AS_Context_v1130_H_ */
#include <asn_internal.h>
