/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-InterNodeDefinitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_AS_Context_NB_H_
#define	_AS_Context_NB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReestablishmentInfo_NB;

/* AS-Context-NB */
typedef struct AS_Context_NB {
	struct ReestablishmentInfo_NB	*reestablishmentInfo_r13	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AS_Context_NB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AS_Context_NB;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReestablishmentInfo-NB.h"

#endif	/* _AS_Context_NB_H_ */
#include <asn_internal.h>
