/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_AS_Config_v1320_H_
#define	_AS_Config_v1320_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SCellToAddModListExt_r13;
struct RCLWI_Configuration_r13;

/* AS-Config-v1320 */
typedef struct AS_Config_v1320 {
	struct SCellToAddModListExt_r13	*sourceSCellConfigList_r13	/* OPTIONAL */;
	struct RCLWI_Configuration_r13	*sourceRCLWI_Configuration_r13	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AS_Config_v1320_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AS_Config_v1320;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SCellToAddModListExt-r13.h"
#include "RCLWI-Configuration-r13.h"

#endif	/* _AS_Config_v1320_H_ */
#include <asn_internal.h>
