/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_CSI_IM_ConfigExt_r12_H_
#define	_CSI_IM_ConfigExt_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CSI-IM-ConfigId-v1250.h"
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include "CSI-IM-ConfigId-v1310.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CSI-IM-ConfigExt-r12 */
typedef struct CSI_IM_ConfigExt_r12 {
	CSI_IM_ConfigId_v1250_t	 csi_IM_ConfigId_v1250;
	long	 resourceConfig_r12;
	long	 subframeConfig_r12;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	BOOLEAN_t	*interferenceMeasRestriction_r13	/* OPTIONAL */;
	CSI_IM_ConfigId_v1310_t	*csi_IM_ConfigId_v1310	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSI_IM_ConfigExt_r12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CSI_IM_ConfigExt_r12;

#ifdef __cplusplus
}
#endif

#endif	/* _CSI_IM_ConfigExt_r12_H_ */
#include <asn_internal.h>
