/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#include "MobilityControlInfo.h"

static int
t304_6_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
t304_6_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
t304_6_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	t304_6_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
t304_6_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	t304_6_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
t304_6_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	t304_6_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
t304_6_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	t304_6_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
t304_6_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	t304_6_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
t304_6_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	t304_6_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
t304_6_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	t304_6_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
t304_6_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	t304_6_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
drb_ContinueROHC_r11_20_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
drb_ContinueROHC_r11_20_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
drb_ContinueROHC_r11_20_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	drb_ContinueROHC_r11_20_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
drb_ContinueROHC_r11_20_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	drb_ContinueROHC_r11_20_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
drb_ContinueROHC_r11_20_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	drb_ContinueROHC_r11_20_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
drb_ContinueROHC_r11_20_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	drb_ContinueROHC_r11_20_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
drb_ContinueROHC_r11_20_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	drb_ContinueROHC_r11_20_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
drb_ContinueROHC_r11_20_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	drb_ContinueROHC_r11_20_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
drb_ContinueROHC_r11_20_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	drb_ContinueROHC_r11_20_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
drb_ContinueROHC_r11_20_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	drb_ContinueROHC_r11_20_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
handoverWithoutWT_Change_r14_23_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
handoverWithoutWT_Change_r14_23_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
handoverWithoutWT_Change_r14_23_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	handoverWithoutWT_Change_r14_23_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
handoverWithoutWT_Change_r14_23_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	handoverWithoutWT_Change_r14_23_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
handoverWithoutWT_Change_r14_23_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	handoverWithoutWT_Change_r14_23_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
handoverWithoutWT_Change_r14_23_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	handoverWithoutWT_Change_r14_23_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
handoverWithoutWT_Change_r14_23_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	handoverWithoutWT_Change_r14_23_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
handoverWithoutWT_Change_r14_23_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	handoverWithoutWT_Change_r14_23_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
handoverWithoutWT_Change_r14_23_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	handoverWithoutWT_Change_r14_23_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
handoverWithoutWT_Change_r14_23_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	handoverWithoutWT_Change_r14_23_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
makeBeforeBreak_r14_26_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
makeBeforeBreak_r14_26_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
makeBeforeBreak_r14_26_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	makeBeforeBreak_r14_26_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
makeBeforeBreak_r14_26_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	makeBeforeBreak_r14_26_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
makeBeforeBreak_r14_26_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	makeBeforeBreak_r14_26_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
makeBeforeBreak_r14_26_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	makeBeforeBreak_r14_26_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
makeBeforeBreak_r14_26_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	makeBeforeBreak_r14_26_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
makeBeforeBreak_r14_26_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	makeBeforeBreak_r14_26_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
makeBeforeBreak_r14_26_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	makeBeforeBreak_r14_26_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
makeBeforeBreak_r14_26_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	makeBeforeBreak_r14_26_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
sameSFN_Indication_r14_29_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
sameSFN_Indication_r14_29_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
sameSFN_Indication_r14_29_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	sameSFN_Indication_r14_29_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
sameSFN_Indication_r14_29_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	sameSFN_Indication_r14_29_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
sameSFN_Indication_r14_29_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	sameSFN_Indication_r14_29_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
sameSFN_Indication_r14_29_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sameSFN_Indication_r14_29_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
sameSFN_Indication_r14_29_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	sameSFN_Indication_r14_29_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
sameSFN_Indication_r14_29_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sameSFN_Indication_r14_29_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
sameSFN_Indication_r14_29_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	sameSFN_Indication_r14_29_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
sameSFN_Indication_r14_29_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	sameSFN_Indication_r14_29_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_t304_constr_6 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_drb_ContinueROHC_r11_constr_20 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_handoverWithoutWT_Change_r14_constr_23 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_makeBeforeBreak_r14_constr_26 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_sameSFN_Indication_r14_constr_29 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_INTEGER_enum_map_t asn_MAP_t304_value2enum_6[] = {
	{ 0,	4,	"ms50" },
	{ 1,	5,	"ms100" },
	{ 2,	5,	"ms150" },
	{ 3,	5,	"ms200" },
	{ 4,	5,	"ms500" },
	{ 5,	6,	"ms1000" },
	{ 6,	6,	"ms2000" },
	{ 7,	13,	"ms10000-v1310" }
};
static unsigned int asn_MAP_t304_enum2value_6[] = {
	1,	/* ms100(1) */
	5,	/* ms1000(5) */
	7,	/* ms10000-v1310(7) */
	2,	/* ms150(2) */
	3,	/* ms200(3) */
	6,	/* ms2000(6) */
	0,	/* ms50(0) */
	4	/* ms500(4) */
};
static asn_INTEGER_specifics_t asn_SPC_t304_specs_6 = {
	asn_MAP_t304_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_t304_enum2value_6,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_t304_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_t304_6 = {
	"t304",
	"t304",
	t304_6_free,
	t304_6_print,
	t304_6_constraint,
	t304_6_decode_ber,
	t304_6_encode_der,
	t304_6_decode_xer,
	t304_6_encode_xer,
	t304_6_decode_uper,
	t304_6_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_t304_tags_6,
	sizeof(asn_DEF_t304_tags_6)
		/sizeof(asn_DEF_t304_tags_6[0]) - 1, /* 1 */
	asn_DEF_t304_tags_6,	/* Same as above */
	sizeof(asn_DEF_t304_tags_6)
		/sizeof(asn_DEF_t304_tags_6[0]), /* 2 */
	&asn_PER_type_t304_constr_6,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_t304_specs_6	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_drb_ContinueROHC_r11_value2enum_20[] = {
	{ 0,	4,	"true" }
};
static unsigned int asn_MAP_drb_ContinueROHC_r11_enum2value_20[] = {
	0	/* true(0) */
};
static asn_INTEGER_specifics_t asn_SPC_drb_ContinueROHC_r11_specs_20 = {
	asn_MAP_drb_ContinueROHC_r11_value2enum_20,	/* "tag" => N; sorted by tag */
	asn_MAP_drb_ContinueROHC_r11_enum2value_20,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_drb_ContinueROHC_r11_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_drb_ContinueROHC_r11_20 = {
	"drb-ContinueROHC-r11",
	"drb-ContinueROHC-r11",
	drb_ContinueROHC_r11_20_free,
	drb_ContinueROHC_r11_20_print,
	drb_ContinueROHC_r11_20_constraint,
	drb_ContinueROHC_r11_20_decode_ber,
	drb_ContinueROHC_r11_20_encode_der,
	drb_ContinueROHC_r11_20_decode_xer,
	drb_ContinueROHC_r11_20_encode_xer,
	drb_ContinueROHC_r11_20_decode_uper,
	drb_ContinueROHC_r11_20_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_drb_ContinueROHC_r11_tags_20,
	sizeof(asn_DEF_drb_ContinueROHC_r11_tags_20)
		/sizeof(asn_DEF_drb_ContinueROHC_r11_tags_20[0]) - 1, /* 1 */
	asn_DEF_drb_ContinueROHC_r11_tags_20,	/* Same as above */
	sizeof(asn_DEF_drb_ContinueROHC_r11_tags_20)
		/sizeof(asn_DEF_drb_ContinueROHC_r11_tags_20[0]), /* 2 */
	&asn_PER_type_drb_ContinueROHC_r11_constr_20,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_drb_ContinueROHC_r11_specs_20	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_handoverWithoutWT_Change_r14_value2enum_23[] = {
	{ 0,	14,	"keepLWA-Config" },
	{ 1,	13,	"sendEndMarker" }
};
static unsigned int asn_MAP_handoverWithoutWT_Change_r14_enum2value_23[] = {
	0,	/* keepLWA-Config(0) */
	1	/* sendEndMarker(1) */
};
static asn_INTEGER_specifics_t asn_SPC_handoverWithoutWT_Change_r14_specs_23 = {
	asn_MAP_handoverWithoutWT_Change_r14_value2enum_23,	/* "tag" => N; sorted by tag */
	asn_MAP_handoverWithoutWT_Change_r14_enum2value_23,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_handoverWithoutWT_Change_r14_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_handoverWithoutWT_Change_r14_23 = {
	"handoverWithoutWT-Change-r14",
	"handoverWithoutWT-Change-r14",
	handoverWithoutWT_Change_r14_23_free,
	handoverWithoutWT_Change_r14_23_print,
	handoverWithoutWT_Change_r14_23_constraint,
	handoverWithoutWT_Change_r14_23_decode_ber,
	handoverWithoutWT_Change_r14_23_encode_der,
	handoverWithoutWT_Change_r14_23_decode_xer,
	handoverWithoutWT_Change_r14_23_encode_xer,
	handoverWithoutWT_Change_r14_23_decode_uper,
	handoverWithoutWT_Change_r14_23_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_handoverWithoutWT_Change_r14_tags_23,
	sizeof(asn_DEF_handoverWithoutWT_Change_r14_tags_23)
		/sizeof(asn_DEF_handoverWithoutWT_Change_r14_tags_23[0]) - 1, /* 1 */
	asn_DEF_handoverWithoutWT_Change_r14_tags_23,	/* Same as above */
	sizeof(asn_DEF_handoverWithoutWT_Change_r14_tags_23)
		/sizeof(asn_DEF_handoverWithoutWT_Change_r14_tags_23[0]), /* 2 */
	&asn_PER_type_handoverWithoutWT_Change_r14_constr_23,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_handoverWithoutWT_Change_r14_specs_23	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_makeBeforeBreak_r14_value2enum_26[] = {
	{ 0,	4,	"true" }
};
static unsigned int asn_MAP_makeBeforeBreak_r14_enum2value_26[] = {
	0	/* true(0) */
};
static asn_INTEGER_specifics_t asn_SPC_makeBeforeBreak_r14_specs_26 = {
	asn_MAP_makeBeforeBreak_r14_value2enum_26,	/* "tag" => N; sorted by tag */
	asn_MAP_makeBeforeBreak_r14_enum2value_26,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_makeBeforeBreak_r14_tags_26[] = {
	(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_makeBeforeBreak_r14_26 = {
	"makeBeforeBreak-r14",
	"makeBeforeBreak-r14",
	makeBeforeBreak_r14_26_free,
	makeBeforeBreak_r14_26_print,
	makeBeforeBreak_r14_26_constraint,
	makeBeforeBreak_r14_26_decode_ber,
	makeBeforeBreak_r14_26_encode_der,
	makeBeforeBreak_r14_26_decode_xer,
	makeBeforeBreak_r14_26_encode_xer,
	makeBeforeBreak_r14_26_decode_uper,
	makeBeforeBreak_r14_26_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_makeBeforeBreak_r14_tags_26,
	sizeof(asn_DEF_makeBeforeBreak_r14_tags_26)
		/sizeof(asn_DEF_makeBeforeBreak_r14_tags_26[0]) - 1, /* 1 */
	asn_DEF_makeBeforeBreak_r14_tags_26,	/* Same as above */
	sizeof(asn_DEF_makeBeforeBreak_r14_tags_26)
		/sizeof(asn_DEF_makeBeforeBreak_r14_tags_26[0]), /* 2 */
	&asn_PER_type_makeBeforeBreak_r14_constr_26,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_makeBeforeBreak_r14_specs_26	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_sameSFN_Indication_r14_value2enum_29[] = {
	{ 0,	4,	"true" }
};
static unsigned int asn_MAP_sameSFN_Indication_r14_enum2value_29[] = {
	0	/* true(0) */
};
static asn_INTEGER_specifics_t asn_SPC_sameSFN_Indication_r14_specs_29 = {
	asn_MAP_sameSFN_Indication_r14_value2enum_29,	/* "tag" => N; sorted by tag */
	asn_MAP_sameSFN_Indication_r14_enum2value_29,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_sameSFN_Indication_r14_tags_29[] = {
	(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sameSFN_Indication_r14_29 = {
	"sameSFN-Indication-r14",
	"sameSFN-Indication-r14",
	sameSFN_Indication_r14_29_free,
	sameSFN_Indication_r14_29_print,
	sameSFN_Indication_r14_29_constraint,
	sameSFN_Indication_r14_29_decode_ber,
	sameSFN_Indication_r14_29_encode_der,
	sameSFN_Indication_r14_29_decode_xer,
	sameSFN_Indication_r14_29_encode_xer,
	sameSFN_Indication_r14_29_decode_uper,
	sameSFN_Indication_r14_29_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sameSFN_Indication_r14_tags_29,
	sizeof(asn_DEF_sameSFN_Indication_r14_tags_29)
		/sizeof(asn_DEF_sameSFN_Indication_r14_tags_29[0]) - 1, /* 1 */
	asn_DEF_sameSFN_Indication_r14_tags_29,	/* Same as above */
	sizeof(asn_DEF_sameSFN_Indication_r14_tags_29)
		/sizeof(asn_DEF_sameSFN_Indication_r14_tags_29[0]), /* 2 */
	&asn_PER_type_sameSFN_Indication_r14_constr_29,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sameSFN_Indication_r14_specs_29	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_MobilityControlInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MobilityControlInfo, targetPhysCellId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"targetPhysCellId"
		},
	{ ATF_POINTER, 3, offsetof(struct MobilityControlInfo, carrierFreq),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CarrierFreqEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"carrierFreq"
		},
	{ ATF_POINTER, 2, offsetof(struct MobilityControlInfo, carrierBandwidth),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CarrierBandwidthEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"carrierBandwidth"
		},
	{ ATF_POINTER, 1, offsetof(struct MobilityControlInfo, additionalSpectrumEmission),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdditionalSpectrumEmission,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"additionalSpectrumEmission"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MobilityControlInfo, t304),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_t304_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"t304"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MobilityControlInfo, newUE_Identity),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_C_RNTI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"newUE-Identity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MobilityControlInfo, radioResourceConfigCommon),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioResourceConfigCommon,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"radioResourceConfigCommon"
		},
	{ ATF_POINTER, 8, offsetof(struct MobilityControlInfo, rach_ConfigDedicated),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RACH_ConfigDedicated,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rach-ConfigDedicated"
		},
	{ ATF_POINTER, 7, offsetof(struct MobilityControlInfo, carrierFreq_v9e0),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CarrierFreqEUTRA_v9e0,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"carrierFreq-v9e0"
		},
	{ ATF_POINTER, 6, offsetof(struct MobilityControlInfo, drb_ContinueROHC_r11),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_drb_ContinueROHC_r11_20,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"drb-ContinueROHC-r11"
		},
	{ ATF_POINTER, 5, offsetof(struct MobilityControlInfo, mobilityControlInfoV2X_r14),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MobilityControlInfoV2X_r14,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mobilityControlInfoV2X-r14"
		},
	{ ATF_POINTER, 4, offsetof(struct MobilityControlInfo, handoverWithoutWT_Change_r14),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_handoverWithoutWT_Change_r14_23,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"handoverWithoutWT-Change-r14"
		},
	{ ATF_POINTER, 3, offsetof(struct MobilityControlInfo, makeBeforeBreak_r14),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_makeBeforeBreak_r14_26,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"makeBeforeBreak-r14"
		},
	{ ATF_POINTER, 2, offsetof(struct MobilityControlInfo, rach_Skip_r14),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RACH_Skip_r14,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rach-Skip-r14"
		},
	{ ATF_POINTER, 1, offsetof(struct MobilityControlInfo, sameSFN_Indication_r14),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sameSFN_Indication_r14_29,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sameSFN-Indication-r14"
		},
};
static int asn_MAP_MobilityControlInfo_oms_1[] = { 1, 2, 3, 7, 8, 9, 10, 11, 12, 13, 14 };
static ber_tlv_tag_t asn_DEF_MobilityControlInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MobilityControlInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* targetPhysCellId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* carrierFreq */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* carrierBandwidth */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* additionalSpectrumEmission */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* t304 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* newUE-Identity */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* radioResourceConfigCommon */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* rach-ConfigDedicated */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* carrierFreq-v9e0 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* drb-ContinueROHC-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* mobilityControlInfoV2X-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* handoverWithoutWT-Change-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* makeBeforeBreak-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* rach-Skip-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 } /* sameSFN-Indication-r14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MobilityControlInfo_specs_1 = {
	sizeof(struct MobilityControlInfo),
	offsetof(struct MobilityControlInfo, _asn_ctx),
	asn_MAP_MobilityControlInfo_tag2el_1,
	15,	/* Count of tags in the map */
	asn_MAP_MobilityControlInfo_oms_1,	/* Optional members */
	4, 7,	/* Root/Additions */
	7,	/* Start extensions */
	16	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MobilityControlInfo = {
	"MobilityControlInfo",
	"MobilityControlInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MobilityControlInfo_tags_1,
	sizeof(asn_DEF_MobilityControlInfo_tags_1)
		/sizeof(asn_DEF_MobilityControlInfo_tags_1[0]), /* 1 */
	asn_DEF_MobilityControlInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_MobilityControlInfo_tags_1)
		/sizeof(asn_DEF_MobilityControlInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MobilityControlInfo_1,
	15,	/* Elements count */
	&asn_SPC_MobilityControlInfo_specs_1	/* Additional specs */
};

