/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#include "OtherConfig-r9.h"

static int
powerPrefIndicationTimer_r11_7_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
powerPrefIndicationTimer_r11_7_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
powerPrefIndicationTimer_r11_7_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	powerPrefIndicationTimer_r11_7_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
powerPrefIndicationTimer_r11_7_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	powerPrefIndicationTimer_r11_7_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
powerPrefIndicationTimer_r11_7_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	powerPrefIndicationTimer_r11_7_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
powerPrefIndicationTimer_r11_7_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	powerPrefIndicationTimer_r11_7_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
powerPrefIndicationTimer_r11_7_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	powerPrefIndicationTimer_r11_7_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
powerPrefIndicationTimer_r11_7_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	powerPrefIndicationTimer_r11_7_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
powerPrefIndicationTimer_r11_7_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	powerPrefIndicationTimer_r11_7_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
powerPrefIndicationTimer_r11_7_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	powerPrefIndicationTimer_r11_7_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
delayBudgetReportingProhibitTimer_r14_28_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
delayBudgetReportingProhibitTimer_r14_28_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
delayBudgetReportingProhibitTimer_r14_28_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	delayBudgetReportingProhibitTimer_r14_28_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
delayBudgetReportingProhibitTimer_r14_28_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	delayBudgetReportingProhibitTimer_r14_28_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
delayBudgetReportingProhibitTimer_r14_28_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	delayBudgetReportingProhibitTimer_r14_28_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
delayBudgetReportingProhibitTimer_r14_28_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	delayBudgetReportingProhibitTimer_r14_28_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
delayBudgetReportingProhibitTimer_r14_28_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	delayBudgetReportingProhibitTimer_r14_28_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
delayBudgetReportingProhibitTimer_r14_28_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	delayBudgetReportingProhibitTimer_r14_28_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
delayBudgetReportingProhibitTimer_r14_28_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	delayBudgetReportingProhibitTimer_r14_28_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
delayBudgetReportingProhibitTimer_r14_28_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	delayBudgetReportingProhibitTimer_r14_28_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
rlmReportTimer_r14_40_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
rlmReportTimer_r14_40_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
rlmReportTimer_r14_40_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	rlmReportTimer_r14_40_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
rlmReportTimer_r14_40_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	rlmReportTimer_r14_40_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
rlmReportTimer_r14_40_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	rlmReportTimer_r14_40_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
rlmReportTimer_r14_40_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	rlmReportTimer_r14_40_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
rlmReportTimer_r14_40_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	rlmReportTimer_r14_40_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
rlmReportTimer_r14_40_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	rlmReportTimer_r14_40_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
rlmReportTimer_r14_40_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	rlmReportTimer_r14_40_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
rlmReportTimer_r14_40_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	rlmReportTimer_r14_40_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
rlmReportRep_MPDCCH_r14_57_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
rlmReportRep_MPDCCH_r14_57_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
rlmReportRep_MPDCCH_r14_57_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	rlmReportRep_MPDCCH_r14_57_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
rlmReportRep_MPDCCH_r14_57_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	rlmReportRep_MPDCCH_r14_57_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
rlmReportRep_MPDCCH_r14_57_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	rlmReportRep_MPDCCH_r14_57_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
rlmReportRep_MPDCCH_r14_57_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	rlmReportRep_MPDCCH_r14_57_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
rlmReportRep_MPDCCH_r14_57_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	rlmReportRep_MPDCCH_r14_57_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
rlmReportRep_MPDCCH_r14_57_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	rlmReportRep_MPDCCH_r14_57_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
rlmReportRep_MPDCCH_r14_57_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	rlmReportRep_MPDCCH_r14_57_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
rlmReportRep_MPDCCH_r14_57_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	rlmReportRep_MPDCCH_r14_57_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_powerPrefIndicationTimer_r11_constr_7 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_delayBudgetReportingProhibitTimer_r14_constr_28 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_delayBudgetReportingConfig_r14_constr_25 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_rlmReportTimer_r14_constr_40 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_rlmReportRep_MPDCCH_r14_constr_57 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_rlm_ReportConfig_r14_constr_37 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_INTEGER_enum_map_t asn_MAP_powerPrefIndicationTimer_r11_value2enum_7[] = {
	{ 0,	2,	"s0" },
	{ 1,	6,	"s0dot5" },
	{ 2,	2,	"s1" },
	{ 3,	2,	"s2" },
	{ 4,	2,	"s5" },
	{ 5,	3,	"s10" },
	{ 6,	3,	"s20" },
	{ 7,	3,	"s30" },
	{ 8,	3,	"s60" },
	{ 9,	3,	"s90" },
	{ 10,	4,	"s120" },
	{ 11,	4,	"s300" },
	{ 12,	4,	"s600" },
	{ 13,	6,	"spare3" },
	{ 14,	6,	"spare2" },
	{ 15,	6,	"spare1" }
};
static unsigned int asn_MAP_powerPrefIndicationTimer_r11_enum2value_7[] = {
	0,	/* s0(0) */
	1,	/* s0dot5(1) */
	2,	/* s1(2) */
	5,	/* s10(5) */
	10,	/* s120(10) */
	3,	/* s2(3) */
	6,	/* s20(6) */
	7,	/* s30(7) */
	11,	/* s300(11) */
	4,	/* s5(4) */
	8,	/* s60(8) */
	12,	/* s600(12) */
	9,	/* s90(9) */
	15,	/* spare1(15) */
	14,	/* spare2(14) */
	13	/* spare3(13) */
};
static asn_INTEGER_specifics_t asn_SPC_powerPrefIndicationTimer_r11_specs_7 = {
	asn_MAP_powerPrefIndicationTimer_r11_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_powerPrefIndicationTimer_r11_enum2value_7,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_powerPrefIndicationTimer_r11_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_powerPrefIndicationTimer_r11_7 = {
	"powerPrefIndicationTimer-r11",
	"powerPrefIndicationTimer-r11",
	powerPrefIndicationTimer_r11_7_free,
	powerPrefIndicationTimer_r11_7_print,
	powerPrefIndicationTimer_r11_7_constraint,
	powerPrefIndicationTimer_r11_7_decode_ber,
	powerPrefIndicationTimer_r11_7_encode_der,
	powerPrefIndicationTimer_r11_7_decode_xer,
	powerPrefIndicationTimer_r11_7_encode_xer,
	powerPrefIndicationTimer_r11_7_decode_uper,
	powerPrefIndicationTimer_r11_7_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_powerPrefIndicationTimer_r11_tags_7,
	sizeof(asn_DEF_powerPrefIndicationTimer_r11_tags_7)
		/sizeof(asn_DEF_powerPrefIndicationTimer_r11_tags_7[0]) - 1, /* 1 */
	asn_DEF_powerPrefIndicationTimer_r11_tags_7,	/* Same as above */
	sizeof(asn_DEF_powerPrefIndicationTimer_r11_tags_7)
		/sizeof(asn_DEF_powerPrefIndicationTimer_r11_tags_7[0]), /* 2 */
	&asn_PER_type_powerPrefIndicationTimer_r11_constr_7,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_powerPrefIndicationTimer_r11_specs_7	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_delayBudgetReportingProhibitTimer_r14_value2enum_28[] = {
	{ 0,	2,	"s0" },
	{ 1,	6,	"s0dot4" },
	{ 2,	6,	"s0dot8" },
	{ 3,	6,	"s1dot6" },
	{ 4,	2,	"s3" },
	{ 5,	2,	"s6" },
	{ 6,	3,	"s12" },
	{ 7,	3,	"s30" }
};
static unsigned int asn_MAP_delayBudgetReportingProhibitTimer_r14_enum2value_28[] = {
	0,	/* s0(0) */
	1,	/* s0dot4(1) */
	2,	/* s0dot8(2) */
	6,	/* s12(6) */
	3,	/* s1dot6(3) */
	4,	/* s3(4) */
	7,	/* s30(7) */
	5	/* s6(5) */
};
static asn_INTEGER_specifics_t asn_SPC_delayBudgetReportingProhibitTimer_r14_specs_28 = {
	asn_MAP_delayBudgetReportingProhibitTimer_r14_value2enum_28,	/* "tag" => N; sorted by tag */
	asn_MAP_delayBudgetReportingProhibitTimer_r14_enum2value_28,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_delayBudgetReportingProhibitTimer_r14_tags_28[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_delayBudgetReportingProhibitTimer_r14_28 = {
	"delayBudgetReportingProhibitTimer-r14",
	"delayBudgetReportingProhibitTimer-r14",
	delayBudgetReportingProhibitTimer_r14_28_free,
	delayBudgetReportingProhibitTimer_r14_28_print,
	delayBudgetReportingProhibitTimer_r14_28_constraint,
	delayBudgetReportingProhibitTimer_r14_28_decode_ber,
	delayBudgetReportingProhibitTimer_r14_28_encode_der,
	delayBudgetReportingProhibitTimer_r14_28_decode_xer,
	delayBudgetReportingProhibitTimer_r14_28_encode_xer,
	delayBudgetReportingProhibitTimer_r14_28_decode_uper,
	delayBudgetReportingProhibitTimer_r14_28_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_delayBudgetReportingProhibitTimer_r14_tags_28,
	sizeof(asn_DEF_delayBudgetReportingProhibitTimer_r14_tags_28)
		/sizeof(asn_DEF_delayBudgetReportingProhibitTimer_r14_tags_28[0]) - 1, /* 1 */
	asn_DEF_delayBudgetReportingProhibitTimer_r14_tags_28,	/* Same as above */
	sizeof(asn_DEF_delayBudgetReportingProhibitTimer_r14_tags_28)
		/sizeof(asn_DEF_delayBudgetReportingProhibitTimer_r14_tags_28[0]), /* 2 */
	&asn_PER_type_delayBudgetReportingProhibitTimer_r14_constr_28,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_delayBudgetReportingProhibitTimer_r14_specs_28	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_27[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OtherConfig_r9__delayBudgetReportingConfig_r14__setup, delayBudgetReportingProhibitTimer_r14),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_delayBudgetReportingProhibitTimer_r14_28,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"delayBudgetReportingProhibitTimer-r14"
		},
};
static ber_tlv_tag_t asn_DEF_setup_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_setup_tag2el_27[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* delayBudgetReportingProhibitTimer-r14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_setup_specs_27 = {
	sizeof(struct OtherConfig_r9__delayBudgetReportingConfig_r14__setup),
	offsetof(struct OtherConfig_r9__delayBudgetReportingConfig_r14__setup, _asn_ctx),
	asn_MAP_setup_tag2el_27,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_27 = {
	"setup",
	"setup",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_setup_tags_27,
	sizeof(asn_DEF_setup_tags_27)
		/sizeof(asn_DEF_setup_tags_27[0]) - 1, /* 1 */
	asn_DEF_setup_tags_27,	/* Same as above */
	sizeof(asn_DEF_setup_tags_27)
		/sizeof(asn_DEF_setup_tags_27[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_setup_27,
	1,	/* Elements count */
	&asn_SPC_setup_specs_27	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_delayBudgetReportingConfig_r14_25[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OtherConfig_r9__delayBudgetReportingConfig_r14, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OtherConfig_r9__delayBudgetReportingConfig_r14, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_27,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static asn_TYPE_tag2member_t asn_MAP_delayBudgetReportingConfig_r14_tag2el_25[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_delayBudgetReportingConfig_r14_specs_25 = {
	sizeof(struct OtherConfig_r9__delayBudgetReportingConfig_r14),
	offsetof(struct OtherConfig_r9__delayBudgetReportingConfig_r14, _asn_ctx),
	offsetof(struct OtherConfig_r9__delayBudgetReportingConfig_r14, present),
	sizeof(((struct OtherConfig_r9__delayBudgetReportingConfig_r14 *)0)->present),
	asn_MAP_delayBudgetReportingConfig_r14_tag2el_25,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_delayBudgetReportingConfig_r14_25 = {
	"delayBudgetReportingConfig-r14",
	"delayBudgetReportingConfig-r14",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_delayBudgetReportingConfig_r14_constr_25,
	asn_MBR_delayBudgetReportingConfig_r14_25,
	2,	/* Elements count */
	&asn_SPC_delayBudgetReportingConfig_r14_specs_25	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_rlmReportTimer_r14_value2enum_40[] = {
	{ 0,	2,	"s0" },
	{ 1,	6,	"s0dot5" },
	{ 2,	2,	"s1" },
	{ 3,	2,	"s2" },
	{ 4,	2,	"s5" },
	{ 5,	3,	"s10" },
	{ 6,	3,	"s20" },
	{ 7,	3,	"s30" },
	{ 8,	3,	"s60" },
	{ 9,	3,	"s90" },
	{ 10,	4,	"s120" },
	{ 11,	4,	"s300" },
	{ 12,	4,	"s600" },
	{ 13,	6,	"spare3" },
	{ 14,	6,	"spare2" },
	{ 15,	6,	"spare1" }
};
static unsigned int asn_MAP_rlmReportTimer_r14_enum2value_40[] = {
	0,	/* s0(0) */
	1,	/* s0dot5(1) */
	2,	/* s1(2) */
	5,	/* s10(5) */
	10,	/* s120(10) */
	3,	/* s2(3) */
	6,	/* s20(6) */
	7,	/* s30(7) */
	11,	/* s300(11) */
	4,	/* s5(4) */
	8,	/* s60(8) */
	12,	/* s600(12) */
	9,	/* s90(9) */
	15,	/* spare1(15) */
	14,	/* spare2(14) */
	13	/* spare3(13) */
};
static asn_INTEGER_specifics_t asn_SPC_rlmReportTimer_r14_specs_40 = {
	asn_MAP_rlmReportTimer_r14_value2enum_40,	/* "tag" => N; sorted by tag */
	asn_MAP_rlmReportTimer_r14_enum2value_40,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_rlmReportTimer_r14_tags_40[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rlmReportTimer_r14_40 = {
	"rlmReportTimer-r14",
	"rlmReportTimer-r14",
	rlmReportTimer_r14_40_free,
	rlmReportTimer_r14_40_print,
	rlmReportTimer_r14_40_constraint,
	rlmReportTimer_r14_40_decode_ber,
	rlmReportTimer_r14_40_encode_der,
	rlmReportTimer_r14_40_decode_xer,
	rlmReportTimer_r14_40_encode_xer,
	rlmReportTimer_r14_40_decode_uper,
	rlmReportTimer_r14_40_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_rlmReportTimer_r14_tags_40,
	sizeof(asn_DEF_rlmReportTimer_r14_tags_40)
		/sizeof(asn_DEF_rlmReportTimer_r14_tags_40[0]) - 1, /* 1 */
	asn_DEF_rlmReportTimer_r14_tags_40,	/* Same as above */
	sizeof(asn_DEF_rlmReportTimer_r14_tags_40)
		/sizeof(asn_DEF_rlmReportTimer_r14_tags_40[0]), /* 2 */
	&asn_PER_type_rlmReportTimer_r14_constr_40,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_rlmReportTimer_r14_specs_40	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_rlmReportRep_MPDCCH_r14_value2enum_57[] = {
	{ 0,	5,	"setup" }
};
static unsigned int asn_MAP_rlmReportRep_MPDCCH_r14_enum2value_57[] = {
	0	/* setup(0) */
};
static asn_INTEGER_specifics_t asn_SPC_rlmReportRep_MPDCCH_r14_specs_57 = {
	asn_MAP_rlmReportRep_MPDCCH_r14_value2enum_57,	/* "tag" => N; sorted by tag */
	asn_MAP_rlmReportRep_MPDCCH_r14_enum2value_57,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_rlmReportRep_MPDCCH_r14_tags_57[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rlmReportRep_MPDCCH_r14_57 = {
	"rlmReportRep-MPDCCH-r14",
	"rlmReportRep-MPDCCH-r14",
	rlmReportRep_MPDCCH_r14_57_free,
	rlmReportRep_MPDCCH_r14_57_print,
	rlmReportRep_MPDCCH_r14_57_constraint,
	rlmReportRep_MPDCCH_r14_57_decode_ber,
	rlmReportRep_MPDCCH_r14_57_encode_der,
	rlmReportRep_MPDCCH_r14_57_decode_xer,
	rlmReportRep_MPDCCH_r14_57_encode_xer,
	rlmReportRep_MPDCCH_r14_57_decode_uper,
	rlmReportRep_MPDCCH_r14_57_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_rlmReportRep_MPDCCH_r14_tags_57,
	sizeof(asn_DEF_rlmReportRep_MPDCCH_r14_tags_57)
		/sizeof(asn_DEF_rlmReportRep_MPDCCH_r14_tags_57[0]) - 1, /* 1 */
	asn_DEF_rlmReportRep_MPDCCH_r14_tags_57,	/* Same as above */
	sizeof(asn_DEF_rlmReportRep_MPDCCH_r14_tags_57)
		/sizeof(asn_DEF_rlmReportRep_MPDCCH_r14_tags_57[0]), /* 2 */
	&asn_PER_type_rlmReportRep_MPDCCH_r14_constr_57,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_rlmReportRep_MPDCCH_r14_specs_57	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_39[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OtherConfig_r9__rlm_ReportConfig_r14__setup, rlmReportTimer_r14),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_rlmReportTimer_r14_40,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rlmReportTimer-r14"
		},
	{ ATF_POINTER, 1, offsetof(struct OtherConfig_r9__rlm_ReportConfig_r14__setup, rlmReportRep_MPDCCH_r14),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_rlmReportRep_MPDCCH_r14_57,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rlmReportRep-MPDCCH-r14"
		},
};
static int asn_MAP_setup_oms_39[] = { 1 };
static ber_tlv_tag_t asn_DEF_setup_tags_39[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_setup_tag2el_39[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rlmReportTimer-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rlmReportRep-MPDCCH-r14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_setup_specs_39 = {
	sizeof(struct OtherConfig_r9__rlm_ReportConfig_r14__setup),
	offsetof(struct OtherConfig_r9__rlm_ReportConfig_r14__setup, _asn_ctx),
	asn_MAP_setup_tag2el_39,
	2,	/* Count of tags in the map */
	asn_MAP_setup_oms_39,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_39 = {
	"setup",
	"setup",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_setup_tags_39,
	sizeof(asn_DEF_setup_tags_39)
		/sizeof(asn_DEF_setup_tags_39[0]) - 1, /* 1 */
	asn_DEF_setup_tags_39,	/* Same as above */
	sizeof(asn_DEF_setup_tags_39)
		/sizeof(asn_DEF_setup_tags_39[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_setup_39,
	2,	/* Elements count */
	&asn_SPC_setup_specs_39	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_rlm_ReportConfig_r14_37[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OtherConfig_r9__rlm_ReportConfig_r14, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OtherConfig_r9__rlm_ReportConfig_r14, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_39,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static asn_TYPE_tag2member_t asn_MAP_rlm_ReportConfig_r14_tag2el_37[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_rlm_ReportConfig_r14_specs_37 = {
	sizeof(struct OtherConfig_r9__rlm_ReportConfig_r14),
	offsetof(struct OtherConfig_r9__rlm_ReportConfig_r14, _asn_ctx),
	offsetof(struct OtherConfig_r9__rlm_ReportConfig_r14, present),
	sizeof(((struct OtherConfig_r9__rlm_ReportConfig_r14 *)0)->present),
	asn_MAP_rlm_ReportConfig_r14_tag2el_37,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rlm_ReportConfig_r14_37 = {
	"rlm-ReportConfig-r14",
	"rlm-ReportConfig-r14",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_rlm_ReportConfig_r14_constr_37,
	asn_MBR_rlm_ReportConfig_r14_37,
	2,	/* Elements count */
	&asn_SPC_rlm_ReportConfig_r14_specs_37	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_OtherConfig_r9_1[] = {
	{ ATF_POINTER, 8, offsetof(struct OtherConfig_r9, reportProximityConfig_r9),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReportProximityConfig_r9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportProximityConfig-r9"
		},
	{ ATF_POINTER, 7, offsetof(struct OtherConfig_r9, idc_Config_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IDC_Config_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"idc-Config-r11"
		},
	{ ATF_POINTER, 6, offsetof(struct OtherConfig_r9, powerPrefIndicationConfig_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PowerPrefIndicationConfig_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"powerPrefIndicationConfig-r11"
		},
	{ ATF_POINTER, 5, offsetof(struct OtherConfig_r9, obtainLocationConfig_r11),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObtainLocationConfig_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"obtainLocationConfig-r11"
		},
	{ ATF_POINTER, 4, offsetof(struct OtherConfig_r9, powerPrefIndicationTimer_r11),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_powerPrefIndicationTimer_r11_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"powerPrefIndicationTimer-r11"
		},
	{ ATF_POINTER, 3, offsetof(struct OtherConfig_r9, sps_AssistanceInfoReport_r14),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sps-AssistanceInfoReport-r14"
		},
	{ ATF_POINTER, 2, offsetof(struct OtherConfig_r9, delayBudgetReportingConfig_r14),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_delayBudgetReportingConfig_r14_25,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"delayBudgetReportingConfig-r14"
		},
	{ ATF_POINTER, 1, offsetof(struct OtherConfig_r9, rlm_ReportConfig_r14),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_rlm_ReportConfig_r14_37,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rlm-ReportConfig-r14"
		},
};
static int asn_MAP_OtherConfig_r9_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
static ber_tlv_tag_t asn_DEF_OtherConfig_r9_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_OtherConfig_r9_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reportProximityConfig-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* idc-Config-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* powerPrefIndicationConfig-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* obtainLocationConfig-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* powerPrefIndicationTimer-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* sps-AssistanceInfoReport-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* delayBudgetReportingConfig-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* rlm-ReportConfig-r14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_OtherConfig_r9_specs_1 = {
	sizeof(struct OtherConfig_r9),
	offsetof(struct OtherConfig_r9, _asn_ctx),
	asn_MAP_OtherConfig_r9_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_OtherConfig_r9_oms_1,	/* Optional members */
	1, 7,	/* Root/Additions */
	0,	/* Start extensions */
	9	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_OtherConfig_r9 = {
	"OtherConfig-r9",
	"OtherConfig-r9",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_OtherConfig_r9_tags_1,
	sizeof(asn_DEF_OtherConfig_r9_tags_1)
		/sizeof(asn_DEF_OtherConfig_r9_tags_1[0]), /* 1 */
	asn_DEF_OtherConfig_r9_tags_1,	/* Same as above */
	sizeof(asn_DEF_OtherConfig_r9_tags_1)
		/sizeof(asn_DEF_OtherConfig_r9_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_OtherConfig_r9_1,
	8,	/* Elements count */
	&asn_SPC_OtherConfig_r9_specs_1	/* Additional specs */
};

