/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#include "RadioResourceConfigDedicatedPSCell-r12.h"

static asn_TYPE_member_t asn_MBR_RadioResourceConfigDedicatedPSCell_r12_1[] = {
	{ ATF_POINTER, 5, offsetof(struct RadioResourceConfigDedicatedPSCell_r12, physicalConfigDedicatedPSCell_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysicalConfigDedicated,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"physicalConfigDedicatedPSCell-r12"
		},
	{ ATF_POINTER, 4, offsetof(struct RadioResourceConfigDedicatedPSCell_r12, sps_Config_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SPS_Config,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sps-Config-r12"
		},
	{ ATF_POINTER, 3, offsetof(struct RadioResourceConfigDedicatedPSCell_r12, naics_Info_r12),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NAICS_AssistanceInfo_r12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"naics-Info-r12"
		},
	{ ATF_POINTER, 2, offsetof(struct RadioResourceConfigDedicatedPSCell_r12, neighCellsCRS_InfoPSCell_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NeighCellsCRS_Info_r13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"neighCellsCRS-InfoPSCell-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct RadioResourceConfigDedicatedPSCell_r12, sps_Config_v1430),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SPS_Config_v1430,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sps-Config-v1430"
		},
};
static int asn_MAP_RadioResourceConfigDedicatedPSCell_r12_oms_1[] = { 0, 1, 2, 3, 4 };
static ber_tlv_tag_t asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RadioResourceConfigDedicatedPSCell_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* physicalConfigDedicatedPSCell-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sps-Config-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* naics-Info-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* neighCellsCRS-InfoPSCell-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* sps-Config-v1430 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RadioResourceConfigDedicatedPSCell_r12_specs_1 = {
	sizeof(struct RadioResourceConfigDedicatedPSCell_r12),
	offsetof(struct RadioResourceConfigDedicatedPSCell_r12, _asn_ctx),
	asn_MAP_RadioResourceConfigDedicatedPSCell_r12_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_RadioResourceConfigDedicatedPSCell_r12_oms_1,	/* Optional members */
	3, 2,	/* Root/Additions */
	2,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RadioResourceConfigDedicatedPSCell_r12 = {
	"RadioResourceConfigDedicatedPSCell-r12",
	"RadioResourceConfigDedicatedPSCell-r12",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1,
	sizeof(asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1)
		/sizeof(asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1[0]), /* 1 */
	asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1)
		/sizeof(asn_DEF_RadioResourceConfigDedicatedPSCell_r12_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RadioResourceConfigDedicatedPSCell_r12_1,
	5,	/* Elements count */
	&asn_SPC_RadioResourceConfigDedicatedPSCell_r12_specs_1	/* Additional specs */
};

