/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_RSRP_Range_v1360_H_
#define	_RSRP_Range_v1360_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RSRP-Range-v1360 */
typedef long	 RSRP_Range_v1360_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RSRP_Range_v1360;
asn_struct_free_f RSRP_Range_v1360_free;
asn_struct_print_f RSRP_Range_v1360_print;
asn_constr_check_f RSRP_Range_v1360_constraint;
ber_type_decoder_f RSRP_Range_v1360_decode_ber;
der_type_encoder_f RSRP_Range_v1360_encode_der;
xer_type_decoder_f RSRP_Range_v1360_decode_xer;
xer_type_encoder_f RSRP_Range_v1360_encode_xer;
per_type_decoder_f RSRP_Range_v1360_decode_uper;
per_type_encoder_f RSRP_Range_v1360_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RSRP_Range_v1360_H_ */
#include <asn_internal.h>
