/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_SPS_ConfigIndex_r14_H_
#define	_SPS_ConfigIndex_r14_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SPS-ConfigIndex-r14 */
typedef long	 SPS_ConfigIndex_r14_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SPS_ConfigIndex_r14;
asn_struct_free_f SPS_ConfigIndex_r14_free;
asn_struct_print_f SPS_ConfigIndex_r14_print;
asn_constr_check_f SPS_ConfigIndex_r14_constraint;
ber_type_decoder_f SPS_ConfigIndex_r14_decode_ber;
der_type_encoder_f SPS_ConfigIndex_r14_encode_der;
xer_type_decoder_f SPS_ConfigIndex_r14_decode_xer;
xer_type_encoder_f SPS_ConfigIndex_r14_encode_xer;
per_type_decoder_f SPS_ConfigIndex_r14_decode_uper;
per_type_encoder_f SPS_ConfigIndex_r14_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SPS_ConfigIndex_r14_H_ */
#include <asn_internal.h>
