/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#include "SystemInformationBlockType20-r13.h"

static int
sc_mcch_RepetitionPeriod_r13_2_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
sc_mcch_RepetitionPeriod_r13_2_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
sc_mcch_RepetitionPeriod_r13_2_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	sc_mcch_RepetitionPeriod_r13_2_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
sc_mcch_RepetitionPeriod_r13_2_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_RepetitionPeriod_r13_2_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_RepetitionPeriod_r13_2_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	sc_mcch_RepetitionPeriod_r13_2_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
sc_mcch_RepetitionPeriod_r13_2_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_RepetitionPeriod_r13_2_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_RepetitionPeriod_r13_2_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	sc_mcch_RepetitionPeriod_r13_2_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
sc_mcch_RepetitionPeriod_r13_2_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_RepetitionPeriod_r13_2_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_RepetitionPeriod_r13_2_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	sc_mcch_RepetitionPeriod_r13_2_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
sc_mcch_RepetitionPeriod_r13_2_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	sc_mcch_RepetitionPeriod_r13_2_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
sc_mcch_ModificationPeriod_r13_14_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
sc_mcch_ModificationPeriod_r13_14_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
sc_mcch_ModificationPeriod_r13_14_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	sc_mcch_ModificationPeriod_r13_14_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
sc_mcch_ModificationPeriod_r13_14_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_ModificationPeriod_r13_14_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_ModificationPeriod_r13_14_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	sc_mcch_ModificationPeriod_r13_14_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
sc_mcch_ModificationPeriod_r13_14_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_ModificationPeriod_r13_14_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_ModificationPeriod_r13_14_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	sc_mcch_ModificationPeriod_r13_14_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
sc_mcch_ModificationPeriod_r13_14_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_ModificationPeriod_r13_14_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_ModificationPeriod_r13_14_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	sc_mcch_ModificationPeriod_r13_14_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
sc_mcch_ModificationPeriod_r13_14_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	sc_mcch_ModificationPeriod_r13_14_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
sc_mcch_RepetitionPeriod_v1430_34_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
sc_mcch_RepetitionPeriod_v1430_34_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
sc_mcch_RepetitionPeriod_v1430_34_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	sc_mcch_RepetitionPeriod_v1430_34_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
sc_mcch_RepetitionPeriod_v1430_34_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_RepetitionPeriod_v1430_34_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_RepetitionPeriod_v1430_34_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	sc_mcch_RepetitionPeriod_v1430_34_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
sc_mcch_RepetitionPeriod_v1430_34_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_RepetitionPeriod_v1430_34_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_RepetitionPeriod_v1430_34_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	sc_mcch_RepetitionPeriod_v1430_34_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
sc_mcch_RepetitionPeriod_v1430_34_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_RepetitionPeriod_v1430_34_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_RepetitionPeriod_v1430_34_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	sc_mcch_RepetitionPeriod_v1430_34_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
sc_mcch_RepetitionPeriod_v1430_34_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	sc_mcch_RepetitionPeriod_v1430_34_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
sc_mcch_ModificationPeriod_v1430_36_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
sc_mcch_ModificationPeriod_v1430_36_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
sc_mcch_ModificationPeriod_v1430_36_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	sc_mcch_ModificationPeriod_v1430_36_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
sc_mcch_ModificationPeriod_v1430_36_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_ModificationPeriod_v1430_36_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_ModificationPeriod_v1430_36_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	sc_mcch_ModificationPeriod_v1430_36_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
sc_mcch_ModificationPeriod_v1430_36_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_ModificationPeriod_v1430_36_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_ModificationPeriod_v1430_36_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	sc_mcch_ModificationPeriod_v1430_36_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
sc_mcch_ModificationPeriod_v1430_36_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_ModificationPeriod_v1430_36_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_ModificationPeriod_v1430_36_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	sc_mcch_ModificationPeriod_v1430_36_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
sc_mcch_ModificationPeriod_v1430_36_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	sc_mcch_ModificationPeriod_v1430_36_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
mpdcch_NumRepetition_SC_MCCH_r14_39_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
mpdcch_NumRepetition_SC_MCCH_r14_39_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
mpdcch_NumRepetition_SC_MCCH_r14_39_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	mpdcch_NumRepetition_SC_MCCH_r14_39_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
mpdcch_NumRepetition_SC_MCCH_r14_39_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_NumRepetition_SC_MCCH_r14_39_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
mpdcch_NumRepetition_SC_MCCH_r14_39_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	mpdcch_NumRepetition_SC_MCCH_r14_39_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
mpdcch_NumRepetition_SC_MCCH_r14_39_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_NumRepetition_SC_MCCH_r14_39_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
mpdcch_NumRepetition_SC_MCCH_r14_39_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	mpdcch_NumRepetition_SC_MCCH_r14_39_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
mpdcch_NumRepetition_SC_MCCH_r14_39_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_NumRepetition_SC_MCCH_r14_39_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
mpdcch_NumRepetition_SC_MCCH_r14_39_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	mpdcch_NumRepetition_SC_MCCH_r14_39_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
mpdcch_NumRepetition_SC_MCCH_r14_39_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	mpdcch_NumRepetition_SC_MCCH_r14_39_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
fdd_r14_50_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
fdd_r14_50_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
fdd_r14_50_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	fdd_r14_50_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
fdd_r14_50_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	fdd_r14_50_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
fdd_r14_50_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	fdd_r14_50_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
fdd_r14_50_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	fdd_r14_50_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
fdd_r14_50_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	fdd_r14_50_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
fdd_r14_50_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	fdd_r14_50_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
fdd_r14_50_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	fdd_r14_50_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
fdd_r14_50_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	fdd_r14_50_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
tdd_r14_59_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
tdd_r14_59_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
tdd_r14_59_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	tdd_r14_59_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
tdd_r14_59_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	tdd_r14_59_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
tdd_r14_59_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	tdd_r14_59_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
tdd_r14_59_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	tdd_r14_59_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
tdd_r14_59_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	tdd_r14_59_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
tdd_r14_59_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	tdd_r14_59_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
tdd_r14_59_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	tdd_r14_59_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
tdd_r14_59_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	tdd_r14_59_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
sc_mcch_RepetitionPeriod_BR_r14_73_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
sc_mcch_RepetitionPeriod_BR_r14_73_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
sc_mcch_RepetitionPeriod_BR_r14_73_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	sc_mcch_RepetitionPeriod_BR_r14_73_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
sc_mcch_RepetitionPeriod_BR_r14_73_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_RepetitionPeriod_BR_r14_73_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_RepetitionPeriod_BR_r14_73_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	sc_mcch_RepetitionPeriod_BR_r14_73_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
sc_mcch_RepetitionPeriod_BR_r14_73_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_RepetitionPeriod_BR_r14_73_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_RepetitionPeriod_BR_r14_73_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	sc_mcch_RepetitionPeriod_BR_r14_73_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
sc_mcch_RepetitionPeriod_BR_r14_73_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_RepetitionPeriod_BR_r14_73_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_RepetitionPeriod_BR_r14_73_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	sc_mcch_RepetitionPeriod_BR_r14_73_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
sc_mcch_RepetitionPeriod_BR_r14_73_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	sc_mcch_RepetitionPeriod_BR_r14_73_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
sc_mcch_ModificationPeriod_BR_r14_82_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
sc_mcch_ModificationPeriod_BR_r14_82_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
sc_mcch_ModificationPeriod_BR_r14_82_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	sc_mcch_ModificationPeriod_BR_r14_82_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
sc_mcch_ModificationPeriod_BR_r14_82_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_ModificationPeriod_BR_r14_82_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_ModificationPeriod_BR_r14_82_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	sc_mcch_ModificationPeriod_BR_r14_82_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
sc_mcch_ModificationPeriod_BR_r14_82_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_ModificationPeriod_BR_r14_82_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_ModificationPeriod_BR_r14_82_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	sc_mcch_ModificationPeriod_BR_r14_82_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
sc_mcch_ModificationPeriod_BR_r14_82_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	sc_mcch_ModificationPeriod_BR_r14_82_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
sc_mcch_ModificationPeriod_BR_r14_82_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	sc_mcch_ModificationPeriod_BR_r14_82_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
sc_mcch_ModificationPeriod_BR_r14_82_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	sc_mcch_ModificationPeriod_BR_r14_82_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
memb_mpdcch_Narrowband_SC_MCCH_r14_constraint_33(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sc_mcch_Offset_BR_r14_constraint_33(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 10)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
memb_sc_mcch_Offset_r13_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 10)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sc_mcch_FirstSubframe_r13_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 9)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sc_mcch_duration_r13_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 2 && value <= 9)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_sc_mcch_RepetitionPeriod_r13_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_sc_mcch_ModificationPeriod_r13_constr_14 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_sc_mcch_RepetitionPeriod_v1430_constr_34 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_sc_mcch_ModificationPeriod_v1430_constr_36 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_mpdcch_NumRepetition_SC_MCCH_r14_constr_39 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  8 }	/* (0..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_fdd_r14_constr_50 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_tdd_r14_constr_59 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_mpdcch_StartSF_SC_MCCH_r14_constr_49 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_constr_67 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_sc_mcch_RepetitionPeriod_BR_r14_constr_73 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_sc_mcch_ModificationPeriod_BR_r14_constr_82 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  14 }	/* (0..14) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_mpdcch_Narrowband_SC_MCCH_r14_constr_38 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  16 }	/* (1..16) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_sc_mcch_Offset_BR_r14_constr_72 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (0..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_constr_99 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_constr_102 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_sc_mcch_Offset_r13_constr_11 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (0..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_sc_mcch_FirstSubframe_r13_constr_12 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_sc_mcch_duration_r13_constr_13 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  2,  9 }	/* (2..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_INTEGER_enum_map_t asn_MAP_sc_mcch_RepetitionPeriod_r13_value2enum_2[] = {
	{ 0,	3,	"rf2" },
	{ 1,	3,	"rf4" },
	{ 2,	3,	"rf8" },
	{ 3,	4,	"rf16" },
	{ 4,	4,	"rf32" },
	{ 5,	4,	"rf64" },
	{ 6,	5,	"rf128" },
	{ 7,	5,	"rf256" }
};
static unsigned int asn_MAP_sc_mcch_RepetitionPeriod_r13_enum2value_2[] = {
	6,	/* rf128(6) */
	3,	/* rf16(3) */
	0,	/* rf2(0) */
	7,	/* rf256(7) */
	4,	/* rf32(4) */
	1,	/* rf4(1) */
	5,	/* rf64(5) */
	2	/* rf8(2) */
};
static asn_INTEGER_specifics_t asn_SPC_sc_mcch_RepetitionPeriod_r13_specs_2 = {
	asn_MAP_sc_mcch_RepetitionPeriod_r13_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_sc_mcch_RepetitionPeriod_r13_enum2value_2,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_sc_mcch_RepetitionPeriod_r13_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sc_mcch_RepetitionPeriod_r13_2 = {
	"sc-mcch-RepetitionPeriod-r13",
	"sc-mcch-RepetitionPeriod-r13",
	sc_mcch_RepetitionPeriod_r13_2_free,
	sc_mcch_RepetitionPeriod_r13_2_print,
	sc_mcch_RepetitionPeriod_r13_2_constraint,
	sc_mcch_RepetitionPeriod_r13_2_decode_ber,
	sc_mcch_RepetitionPeriod_r13_2_encode_der,
	sc_mcch_RepetitionPeriod_r13_2_decode_xer,
	sc_mcch_RepetitionPeriod_r13_2_encode_xer,
	sc_mcch_RepetitionPeriod_r13_2_decode_uper,
	sc_mcch_RepetitionPeriod_r13_2_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sc_mcch_RepetitionPeriod_r13_tags_2,
	sizeof(asn_DEF_sc_mcch_RepetitionPeriod_r13_tags_2)
		/sizeof(asn_DEF_sc_mcch_RepetitionPeriod_r13_tags_2[0]) - 1, /* 1 */
	asn_DEF_sc_mcch_RepetitionPeriod_r13_tags_2,	/* Same as above */
	sizeof(asn_DEF_sc_mcch_RepetitionPeriod_r13_tags_2)
		/sizeof(asn_DEF_sc_mcch_RepetitionPeriod_r13_tags_2[0]), /* 2 */
	&asn_PER_type_sc_mcch_RepetitionPeriod_r13_constr_2,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sc_mcch_RepetitionPeriod_r13_specs_2	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_sc_mcch_ModificationPeriod_r13_value2enum_14[] = {
	{ 0,	3,	"rf2" },
	{ 1,	3,	"rf4" },
	{ 2,	3,	"rf8" },
	{ 3,	4,	"rf16" },
	{ 4,	4,	"rf32" },
	{ 5,	4,	"rf64" },
	{ 6,	5,	"rf128" },
	{ 7,	5,	"rf256" },
	{ 8,	5,	"rf512" },
	{ 9,	6,	"rf1024" },
	{ 10,	5,	"r2048" },
	{ 11,	6,	"rf4096" },
	{ 12,	6,	"rf8192" },
	{ 13,	7,	"rf16384" },
	{ 14,	7,	"rf32768" },
	{ 15,	7,	"rf65536" }
};
static unsigned int asn_MAP_sc_mcch_ModificationPeriod_r13_enum2value_14[] = {
	10,	/* r2048(10) */
	9,	/* rf1024(9) */
	6,	/* rf128(6) */
	3,	/* rf16(3) */
	13,	/* rf16384(13) */
	0,	/* rf2(0) */
	7,	/* rf256(7) */
	4,	/* rf32(4) */
	14,	/* rf32768(14) */
	1,	/* rf4(1) */
	11,	/* rf4096(11) */
	8,	/* rf512(8) */
	5,	/* rf64(5) */
	15,	/* rf65536(15) */
	2,	/* rf8(2) */
	12	/* rf8192(12) */
};
static asn_INTEGER_specifics_t asn_SPC_sc_mcch_ModificationPeriod_r13_specs_14 = {
	asn_MAP_sc_mcch_ModificationPeriod_r13_value2enum_14,	/* "tag" => N; sorted by tag */
	asn_MAP_sc_mcch_ModificationPeriod_r13_enum2value_14,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_sc_mcch_ModificationPeriod_r13_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sc_mcch_ModificationPeriod_r13_14 = {
	"sc-mcch-ModificationPeriod-r13",
	"sc-mcch-ModificationPeriod-r13",
	sc_mcch_ModificationPeriod_r13_14_free,
	sc_mcch_ModificationPeriod_r13_14_print,
	sc_mcch_ModificationPeriod_r13_14_constraint,
	sc_mcch_ModificationPeriod_r13_14_decode_ber,
	sc_mcch_ModificationPeriod_r13_14_encode_der,
	sc_mcch_ModificationPeriod_r13_14_decode_xer,
	sc_mcch_ModificationPeriod_r13_14_encode_xer,
	sc_mcch_ModificationPeriod_r13_14_decode_uper,
	sc_mcch_ModificationPeriod_r13_14_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sc_mcch_ModificationPeriod_r13_tags_14,
	sizeof(asn_DEF_sc_mcch_ModificationPeriod_r13_tags_14)
		/sizeof(asn_DEF_sc_mcch_ModificationPeriod_r13_tags_14[0]) - 1, /* 1 */
	asn_DEF_sc_mcch_ModificationPeriod_r13_tags_14,	/* Same as above */
	sizeof(asn_DEF_sc_mcch_ModificationPeriod_r13_tags_14)
		/sizeof(asn_DEF_sc_mcch_ModificationPeriod_r13_tags_14[0]), /* 2 */
	&asn_PER_type_sc_mcch_ModificationPeriod_r13_constr_14,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sc_mcch_ModificationPeriod_r13_specs_14	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_sc_mcch_RepetitionPeriod_v1430_value2enum_34[] = {
	{ 0,	3,	"rf1" }
};
static unsigned int asn_MAP_sc_mcch_RepetitionPeriod_v1430_enum2value_34[] = {
	0	/* rf1(0) */
};
static asn_INTEGER_specifics_t asn_SPC_sc_mcch_RepetitionPeriod_v1430_specs_34 = {
	asn_MAP_sc_mcch_RepetitionPeriod_v1430_value2enum_34,	/* "tag" => N; sorted by tag */
	asn_MAP_sc_mcch_RepetitionPeriod_v1430_enum2value_34,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_sc_mcch_RepetitionPeriod_v1430_tags_34[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sc_mcch_RepetitionPeriod_v1430_34 = {
	"sc-mcch-RepetitionPeriod-v1430",
	"sc-mcch-RepetitionPeriod-v1430",
	sc_mcch_RepetitionPeriod_v1430_34_free,
	sc_mcch_RepetitionPeriod_v1430_34_print,
	sc_mcch_RepetitionPeriod_v1430_34_constraint,
	sc_mcch_RepetitionPeriod_v1430_34_decode_ber,
	sc_mcch_RepetitionPeriod_v1430_34_encode_der,
	sc_mcch_RepetitionPeriod_v1430_34_decode_xer,
	sc_mcch_RepetitionPeriod_v1430_34_encode_xer,
	sc_mcch_RepetitionPeriod_v1430_34_decode_uper,
	sc_mcch_RepetitionPeriod_v1430_34_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sc_mcch_RepetitionPeriod_v1430_tags_34,
	sizeof(asn_DEF_sc_mcch_RepetitionPeriod_v1430_tags_34)
		/sizeof(asn_DEF_sc_mcch_RepetitionPeriod_v1430_tags_34[0]) - 1, /* 1 */
	asn_DEF_sc_mcch_RepetitionPeriod_v1430_tags_34,	/* Same as above */
	sizeof(asn_DEF_sc_mcch_RepetitionPeriod_v1430_tags_34)
		/sizeof(asn_DEF_sc_mcch_RepetitionPeriod_v1430_tags_34[0]), /* 2 */
	&asn_PER_type_sc_mcch_RepetitionPeriod_v1430_constr_34,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sc_mcch_RepetitionPeriod_v1430_specs_34	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_sc_mcch_ModificationPeriod_v1430_value2enum_36[] = {
	{ 0,	3,	"rf1" }
};
static unsigned int asn_MAP_sc_mcch_ModificationPeriod_v1430_enum2value_36[] = {
	0	/* rf1(0) */
};
static asn_INTEGER_specifics_t asn_SPC_sc_mcch_ModificationPeriod_v1430_specs_36 = {
	asn_MAP_sc_mcch_ModificationPeriod_v1430_value2enum_36,	/* "tag" => N; sorted by tag */
	asn_MAP_sc_mcch_ModificationPeriod_v1430_enum2value_36,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_sc_mcch_ModificationPeriod_v1430_tags_36[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sc_mcch_ModificationPeriod_v1430_36 = {
	"sc-mcch-ModificationPeriod-v1430",
	"sc-mcch-ModificationPeriod-v1430",
	sc_mcch_ModificationPeriod_v1430_36_free,
	sc_mcch_ModificationPeriod_v1430_36_print,
	sc_mcch_ModificationPeriod_v1430_36_constraint,
	sc_mcch_ModificationPeriod_v1430_36_decode_ber,
	sc_mcch_ModificationPeriod_v1430_36_encode_der,
	sc_mcch_ModificationPeriod_v1430_36_decode_xer,
	sc_mcch_ModificationPeriod_v1430_36_encode_xer,
	sc_mcch_ModificationPeriod_v1430_36_decode_uper,
	sc_mcch_ModificationPeriod_v1430_36_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sc_mcch_ModificationPeriod_v1430_tags_36,
	sizeof(asn_DEF_sc_mcch_ModificationPeriod_v1430_tags_36)
		/sizeof(asn_DEF_sc_mcch_ModificationPeriod_v1430_tags_36[0]) - 1, /* 1 */
	asn_DEF_sc_mcch_ModificationPeriod_v1430_tags_36,	/* Same as above */
	sizeof(asn_DEF_sc_mcch_ModificationPeriod_v1430_tags_36)
		/sizeof(asn_DEF_sc_mcch_ModificationPeriod_v1430_tags_36[0]), /* 2 */
	&asn_PER_type_sc_mcch_ModificationPeriod_v1430_constr_36,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sc_mcch_ModificationPeriod_v1430_specs_36	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_mpdcch_NumRepetition_SC_MCCH_r14_value2enum_39[] = {
	{ 0,	2,	"r1" },
	{ 1,	2,	"r2" },
	{ 2,	2,	"r4" },
	{ 3,	2,	"r8" },
	{ 4,	3,	"r16" },
	{ 5,	3,	"r32" },
	{ 6,	3,	"r64" },
	{ 7,	4,	"r128" },
	{ 8,	4,	"r256" }
};
static unsigned int asn_MAP_mpdcch_NumRepetition_SC_MCCH_r14_enum2value_39[] = {
	0,	/* r1(0) */
	7,	/* r128(7) */
	4,	/* r16(4) */
	1,	/* r2(1) */
	8,	/* r256(8) */
	5,	/* r32(5) */
	2,	/* r4(2) */
	6,	/* r64(6) */
	3	/* r8(3) */
};
static asn_INTEGER_specifics_t asn_SPC_mpdcch_NumRepetition_SC_MCCH_r14_specs_39 = {
	asn_MAP_mpdcch_NumRepetition_SC_MCCH_r14_value2enum_39,	/* "tag" => N; sorted by tag */
	asn_MAP_mpdcch_NumRepetition_SC_MCCH_r14_enum2value_39,	/* N => "tag"; sorted by N */
	9,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_mpdcch_NumRepetition_SC_MCCH_r14_tags_39[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mpdcch_NumRepetition_SC_MCCH_r14_39 = {
	"mpdcch-NumRepetition-SC-MCCH-r14",
	"mpdcch-NumRepetition-SC-MCCH-r14",
	mpdcch_NumRepetition_SC_MCCH_r14_39_free,
	mpdcch_NumRepetition_SC_MCCH_r14_39_print,
	mpdcch_NumRepetition_SC_MCCH_r14_39_constraint,
	mpdcch_NumRepetition_SC_MCCH_r14_39_decode_ber,
	mpdcch_NumRepetition_SC_MCCH_r14_39_encode_der,
	mpdcch_NumRepetition_SC_MCCH_r14_39_decode_xer,
	mpdcch_NumRepetition_SC_MCCH_r14_39_encode_xer,
	mpdcch_NumRepetition_SC_MCCH_r14_39_decode_uper,
	mpdcch_NumRepetition_SC_MCCH_r14_39_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mpdcch_NumRepetition_SC_MCCH_r14_tags_39,
	sizeof(asn_DEF_mpdcch_NumRepetition_SC_MCCH_r14_tags_39)
		/sizeof(asn_DEF_mpdcch_NumRepetition_SC_MCCH_r14_tags_39[0]) - 1, /* 1 */
	asn_DEF_mpdcch_NumRepetition_SC_MCCH_r14_tags_39,	/* Same as above */
	sizeof(asn_DEF_mpdcch_NumRepetition_SC_MCCH_r14_tags_39)
		/sizeof(asn_DEF_mpdcch_NumRepetition_SC_MCCH_r14_tags_39[0]), /* 2 */
	&asn_PER_type_mpdcch_NumRepetition_SC_MCCH_r14_constr_39,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mpdcch_NumRepetition_SC_MCCH_r14_specs_39	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_fdd_r14_value2enum_50[] = {
	{ 0,	2,	"v1" },
	{ 1,	6,	"v1dot5" },
	{ 2,	2,	"v2" },
	{ 3,	6,	"v2dot5" },
	{ 4,	2,	"v4" },
	{ 5,	2,	"v5" },
	{ 6,	2,	"v8" },
	{ 7,	3,	"v10" }
};
static unsigned int asn_MAP_fdd_r14_enum2value_50[] = {
	0,	/* v1(0) */
	7,	/* v10(7) */
	1,	/* v1dot5(1) */
	2,	/* v2(2) */
	3,	/* v2dot5(3) */
	4,	/* v4(4) */
	5,	/* v5(5) */
	6	/* v8(6) */
};
static asn_INTEGER_specifics_t asn_SPC_fdd_r14_specs_50 = {
	asn_MAP_fdd_r14_value2enum_50,	/* "tag" => N; sorted by tag */
	asn_MAP_fdd_r14_enum2value_50,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_fdd_r14_tags_50[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_fdd_r14_50 = {
	"fdd-r14",
	"fdd-r14",
	fdd_r14_50_free,
	fdd_r14_50_print,
	fdd_r14_50_constraint,
	fdd_r14_50_decode_ber,
	fdd_r14_50_encode_der,
	fdd_r14_50_decode_xer,
	fdd_r14_50_encode_xer,
	fdd_r14_50_decode_uper,
	fdd_r14_50_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_fdd_r14_tags_50,
	sizeof(asn_DEF_fdd_r14_tags_50)
		/sizeof(asn_DEF_fdd_r14_tags_50[0]) - 1, /* 1 */
	asn_DEF_fdd_r14_tags_50,	/* Same as above */
	sizeof(asn_DEF_fdd_r14_tags_50)
		/sizeof(asn_DEF_fdd_r14_tags_50[0]), /* 2 */
	&asn_PER_type_fdd_r14_constr_50,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_fdd_r14_specs_50	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_tdd_r14_value2enum_59[] = {
	{ 0,	2,	"v1" },
	{ 1,	2,	"v2" },
	{ 2,	2,	"v4" },
	{ 3,	2,	"v5" },
	{ 4,	2,	"v8" },
	{ 5,	3,	"v10" },
	{ 6,	3,	"v20" }
};
static unsigned int asn_MAP_tdd_r14_enum2value_59[] = {
	0,	/* v1(0) */
	5,	/* v10(5) */
	1,	/* v2(1) */
	6,	/* v20(6) */
	2,	/* v4(2) */
	3,	/* v5(3) */
	4	/* v8(4) */
};
static asn_INTEGER_specifics_t asn_SPC_tdd_r14_specs_59 = {
	asn_MAP_tdd_r14_value2enum_59,	/* "tag" => N; sorted by tag */
	asn_MAP_tdd_r14_enum2value_59,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_tdd_r14_tags_59[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tdd_r14_59 = {
	"tdd-r14",
	"tdd-r14",
	tdd_r14_59_free,
	tdd_r14_59_print,
	tdd_r14_59_constraint,
	tdd_r14_59_decode_ber,
	tdd_r14_59_encode_der,
	tdd_r14_59_decode_xer,
	tdd_r14_59_encode_xer,
	tdd_r14_59_decode_uper,
	tdd_r14_59_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_tdd_r14_tags_59,
	sizeof(asn_DEF_tdd_r14_tags_59)
		/sizeof(asn_DEF_tdd_r14_tags_59[0]) - 1, /* 1 */
	asn_DEF_tdd_r14_tags_59,	/* Same as above */
	sizeof(asn_DEF_tdd_r14_tags_59)
		/sizeof(asn_DEF_tdd_r14_tags_59[0]), /* 2 */
	&asn_PER_type_tdd_r14_constr_59,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_tdd_r14_specs_59	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_mpdcch_StartSF_SC_MCCH_r14_49[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14__mpdcch_StartSF_SC_MCCH_r14, choice.fdd_r14),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_fdd_r14_50,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"fdd-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14__mpdcch_StartSF_SC_MCCH_r14, choice.tdd_r14),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_tdd_r14_59,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tdd-r14"
		},
};
static asn_TYPE_tag2member_t asn_MAP_mpdcch_StartSF_SC_MCCH_r14_tag2el_49[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd-r14 */
};
static asn_CHOICE_specifics_t asn_SPC_mpdcch_StartSF_SC_MCCH_r14_specs_49 = {
	sizeof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14__mpdcch_StartSF_SC_MCCH_r14),
	offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14__mpdcch_StartSF_SC_MCCH_r14, _asn_ctx),
	offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14__mpdcch_StartSF_SC_MCCH_r14, present),
	sizeof(((struct SystemInformationBlockType20_r13__br_BCCH_Config_r14__mpdcch_StartSF_SC_MCCH_r14 *)0)->present),
	asn_MAP_mpdcch_StartSF_SC_MCCH_r14_tag2el_49,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mpdcch_StartSF_SC_MCCH_r14_49 = {
	"mpdcch-StartSF-SC-MCCH-r14",
	"mpdcch-StartSF-SC-MCCH-r14",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_mpdcch_StartSF_SC_MCCH_r14_constr_49,
	asn_MBR_mpdcch_StartSF_SC_MCCH_r14_49,
	2,	/* Elements count */
	&asn_SPC_mpdcch_StartSF_SC_MCCH_r14_specs_49	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_value2enum_67[] = {
	{ 0,	3,	"off" },
	{ 1,	8,	"ce-ModeA" },
	{ 2,	8,	"ce-ModeB" }
};
static unsigned int asn_MAP_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_enum2value_67[] = {
	1,	/* ce-ModeA(1) */
	2,	/* ce-ModeB(2) */
	0	/* off(0) */
};
static asn_INTEGER_specifics_t asn_SPC_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_specs_67 = {
	asn_MAP_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_value2enum_67,	/* "tag" => N; sorted by tag */
	asn_MAP_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_enum2value_67,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_tags_67[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67 = {
	"mpdcch-PDSCH-HoppingConfig-SC-MCCH-r14",
	"mpdcch-PDSCH-HoppingConfig-SC-MCCH-r14",
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_free,
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_print,
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_constraint,
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_decode_ber,
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_encode_der,
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_decode_xer,
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_encode_xer,
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_decode_uper,
	mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_tags_67,
	sizeof(asn_DEF_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_tags_67)
		/sizeof(asn_DEF_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_tags_67[0]) - 1, /* 1 */
	asn_DEF_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_tags_67,	/* Same as above */
	sizeof(asn_DEF_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_tags_67)
		/sizeof(asn_DEF_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_tags_67[0]), /* 2 */
	&asn_PER_type_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_constr_67,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_specs_67	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_sc_mcch_RepetitionPeriod_BR_r14_value2enum_73[] = {
	{ 0,	4,	"rf32" },
	{ 1,	5,	"rf128" },
	{ 2,	5,	"rf512" },
	{ 3,	6,	"rf1024" },
	{ 4,	6,	"rf2048" },
	{ 5,	6,	"rf4096" },
	{ 6,	6,	"rf8192" },
	{ 7,	7,	"rf16384" }
};
static unsigned int asn_MAP_sc_mcch_RepetitionPeriod_BR_r14_enum2value_73[] = {
	3,	/* rf1024(3) */
	1,	/* rf128(1) */
	7,	/* rf16384(7) */
	4,	/* rf2048(4) */
	0,	/* rf32(0) */
	5,	/* rf4096(5) */
	2,	/* rf512(2) */
	6	/* rf8192(6) */
};
static asn_INTEGER_specifics_t asn_SPC_sc_mcch_RepetitionPeriod_BR_r14_specs_73 = {
	asn_MAP_sc_mcch_RepetitionPeriod_BR_r14_value2enum_73,	/* "tag" => N; sorted by tag */
	asn_MAP_sc_mcch_RepetitionPeriod_BR_r14_enum2value_73,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_sc_mcch_RepetitionPeriod_BR_r14_tags_73[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sc_mcch_RepetitionPeriod_BR_r14_73 = {
	"sc-mcch-RepetitionPeriod-BR-r14",
	"sc-mcch-RepetitionPeriod-BR-r14",
	sc_mcch_RepetitionPeriod_BR_r14_73_free,
	sc_mcch_RepetitionPeriod_BR_r14_73_print,
	sc_mcch_RepetitionPeriod_BR_r14_73_constraint,
	sc_mcch_RepetitionPeriod_BR_r14_73_decode_ber,
	sc_mcch_RepetitionPeriod_BR_r14_73_encode_der,
	sc_mcch_RepetitionPeriod_BR_r14_73_decode_xer,
	sc_mcch_RepetitionPeriod_BR_r14_73_encode_xer,
	sc_mcch_RepetitionPeriod_BR_r14_73_decode_uper,
	sc_mcch_RepetitionPeriod_BR_r14_73_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sc_mcch_RepetitionPeriod_BR_r14_tags_73,
	sizeof(asn_DEF_sc_mcch_RepetitionPeriod_BR_r14_tags_73)
		/sizeof(asn_DEF_sc_mcch_RepetitionPeriod_BR_r14_tags_73[0]) - 1, /* 1 */
	asn_DEF_sc_mcch_RepetitionPeriod_BR_r14_tags_73,	/* Same as above */
	sizeof(asn_DEF_sc_mcch_RepetitionPeriod_BR_r14_tags_73)
		/sizeof(asn_DEF_sc_mcch_RepetitionPeriod_BR_r14_tags_73[0]), /* 2 */
	&asn_PER_type_sc_mcch_RepetitionPeriod_BR_r14_constr_73,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sc_mcch_RepetitionPeriod_BR_r14_specs_73	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_sc_mcch_ModificationPeriod_BR_r14_value2enum_82[] = {
	{ 0,	4,	"rf32" },
	{ 1,	5,	"rf128" },
	{ 2,	5,	"rf256" },
	{ 3,	5,	"rf512" },
	{ 4,	6,	"rf1024" },
	{ 5,	6,	"rf2048" },
	{ 6,	6,	"rf4096" },
	{ 7,	6,	"rf8192" },
	{ 8,	7,	"rf16384" },
	{ 9,	7,	"rf32768" },
	{ 10,	7,	"rf65536" },
	{ 11,	8,	"rf131072" },
	{ 12,	8,	"rf262144" },
	{ 13,	8,	"rf524288" },
	{ 14,	9,	"rf1048576" }
};
static unsigned int asn_MAP_sc_mcch_ModificationPeriod_BR_r14_enum2value_82[] = {
	4,	/* rf1024(4) */
	14,	/* rf1048576(14) */
	1,	/* rf128(1) */
	11,	/* rf131072(11) */
	8,	/* rf16384(8) */
	5,	/* rf2048(5) */
	2,	/* rf256(2) */
	12,	/* rf262144(12) */
	0,	/* rf32(0) */
	9,	/* rf32768(9) */
	6,	/* rf4096(6) */
	3,	/* rf512(3) */
	13,	/* rf524288(13) */
	10,	/* rf65536(10) */
	7	/* rf8192(7) */
};
static asn_INTEGER_specifics_t asn_SPC_sc_mcch_ModificationPeriod_BR_r14_specs_82 = {
	asn_MAP_sc_mcch_ModificationPeriod_BR_r14_value2enum_82,	/* "tag" => N; sorted by tag */
	asn_MAP_sc_mcch_ModificationPeriod_BR_r14_enum2value_82,	/* N => "tag"; sorted by N */
	15,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_sc_mcch_ModificationPeriod_BR_r14_tags_82[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sc_mcch_ModificationPeriod_BR_r14_82 = {
	"sc-mcch-ModificationPeriod-BR-r14",
	"sc-mcch-ModificationPeriod-BR-r14",
	sc_mcch_ModificationPeriod_BR_r14_82_free,
	sc_mcch_ModificationPeriod_BR_r14_82_print,
	sc_mcch_ModificationPeriod_BR_r14_82_constraint,
	sc_mcch_ModificationPeriod_BR_r14_82_decode_ber,
	sc_mcch_ModificationPeriod_BR_r14_82_encode_der,
	sc_mcch_ModificationPeriod_BR_r14_82_decode_xer,
	sc_mcch_ModificationPeriod_BR_r14_82_encode_xer,
	sc_mcch_ModificationPeriod_BR_r14_82_decode_uper,
	sc_mcch_ModificationPeriod_BR_r14_82_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_sc_mcch_ModificationPeriod_BR_r14_tags_82,
	sizeof(asn_DEF_sc_mcch_ModificationPeriod_BR_r14_tags_82)
		/sizeof(asn_DEF_sc_mcch_ModificationPeriod_BR_r14_tags_82[0]) - 1, /* 1 */
	asn_DEF_sc_mcch_ModificationPeriod_BR_r14_tags_82,	/* Same as above */
	sizeof(asn_DEF_sc_mcch_ModificationPeriod_BR_r14_tags_82)
		/sizeof(asn_DEF_sc_mcch_ModificationPeriod_BR_r14_tags_82[0]), /* 2 */
	&asn_PER_type_sc_mcch_ModificationPeriod_BR_r14_constr_82,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sc_mcch_ModificationPeriod_BR_r14_specs_82	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_br_BCCH_Config_r14_33[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, sc_mcch_RepetitionPeriod_v1430),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sc_mcch_RepetitionPeriod_v1430_34,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sc-mcch-RepetitionPeriod-v1430"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, sc_mcch_ModificationPeriod_v1430),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sc_mcch_ModificationPeriod_v1430_36,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sc-mcch-ModificationPeriod-v1430"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, mpdcch_Narrowband_SC_MCCH_r14),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_mpdcch_Narrowband_SC_MCCH_r14_constraint_33,
		&asn_PER_memb_mpdcch_Narrowband_SC_MCCH_r14_constr_38,
		0,
		"mpdcch-Narrowband-SC-MCCH-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, mpdcch_NumRepetition_SC_MCCH_r14),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mpdcch_NumRepetition_SC_MCCH_r14_39,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mpdcch-NumRepetition-SC-MCCH-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, mpdcch_StartSF_SC_MCCH_r14),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_mpdcch_StartSF_SC_MCCH_r14_49,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mpdcch-StartSF-SC-MCCH-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mpdcch_PDSCH_HoppingConfig_SC_MCCH_r14_67,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mpdcch-PDSCH-HoppingConfig-SC-MCCH-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, sc_mcch_CarrierFreq_r14),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueEUTRA_r9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sc-mcch-CarrierFreq-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, sc_mcch_Offset_BR_r14),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_sc_mcch_Offset_BR_r14_constraint_33,
		&asn_PER_memb_sc_mcch_Offset_BR_r14_constr_72,
		0,
		"sc-mcch-Offset-BR-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, sc_mcch_RepetitionPeriod_BR_r14),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sc_mcch_RepetitionPeriod_BR_r14_73,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sc-mcch-RepetitionPeriod-BR-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, sc_mcch_ModificationPeriod_BR_r14),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sc_mcch_ModificationPeriod_BR_r14_82,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sc-mcch-ModificationPeriod-BR-r14"
		},
};
static ber_tlv_tag_t asn_DEF_br_BCCH_Config_r14_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_br_BCCH_Config_r14_tag2el_33[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sc-mcch-RepetitionPeriod-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sc-mcch-ModificationPeriod-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* mpdcch-Narrowband-SC-MCCH-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mpdcch-NumRepetition-SC-MCCH-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* mpdcch-StartSF-SC-MCCH-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* mpdcch-PDSCH-HoppingConfig-SC-MCCH-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* sc-mcch-CarrierFreq-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* sc-mcch-Offset-BR-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* sc-mcch-RepetitionPeriod-BR-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* sc-mcch-ModificationPeriod-BR-r14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_br_BCCH_Config_r14_specs_33 = {
	sizeof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14),
	offsetof(struct SystemInformationBlockType20_r13__br_BCCH_Config_r14, _asn_ctx),
	asn_MAP_br_BCCH_Config_r14_tag2el_33,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_br_BCCH_Config_r14_33 = {
	"br-BCCH-Config-r14",
	"br-BCCH-Config-r14",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_br_BCCH_Config_r14_tags_33,
	sizeof(asn_DEF_br_BCCH_Config_r14_tags_33)
		/sizeof(asn_DEF_br_BCCH_Config_r14_tags_33[0]) - 1, /* 1 */
	asn_DEF_br_BCCH_Config_r14_tags_33,	/* Same as above */
	sizeof(asn_DEF_br_BCCH_Config_r14_tags_33)
		/sizeof(asn_DEF_br_BCCH_Config_r14_tags_33[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_br_BCCH_Config_r14_33,
	10,	/* Elements count */
	&asn_SPC_br_BCCH_Config_r14_specs_33	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_value2enum_99[] = {
	{ 0,	3,	"r16" },
	{ 1,	3,	"r32" }
};
static unsigned int asn_MAP_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_enum2value_99[] = {
	0,	/* r16(0) */
	1	/* r32(1) */
};
static asn_INTEGER_specifics_t asn_SPC_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_specs_99 = {
	asn_MAP_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_value2enum_99,	/* "tag" => N; sorted by tag */
	asn_MAP_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_enum2value_99,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_tags_99[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99 = {
	"pdsch-maxNumRepetitionCEmodeA-SC-MTCH-r14",
	"pdsch-maxNumRepetitionCEmodeA-SC-MTCH-r14",
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_free,
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_print,
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_constraint,
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_decode_ber,
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_encode_der,
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_decode_xer,
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_encode_xer,
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_decode_uper,
	pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_tags_99,
	sizeof(asn_DEF_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_tags_99)
		/sizeof(asn_DEF_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_tags_99[0]) - 1, /* 1 */
	asn_DEF_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_tags_99,	/* Same as above */
	sizeof(asn_DEF_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_tags_99)
		/sizeof(asn_DEF_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_tags_99[0]), /* 2 */
	&asn_PER_type_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_constr_99,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_specs_99	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_value2enum_102[] = {
	{ 0,	4,	"r192" },
	{ 1,	4,	"r256" },
	{ 2,	4,	"r384" },
	{ 3,	4,	"r512" },
	{ 4,	4,	"r768" },
	{ 5,	5,	"r1024" },
	{ 6,	5,	"r1536" },
	{ 7,	5,	"r2048" }
};
static unsigned int asn_MAP_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_enum2value_102[] = {
	5,	/* r1024(5) */
	6,	/* r1536(6) */
	0,	/* r192(0) */
	7,	/* r2048(7) */
	1,	/* r256(1) */
	2,	/* r384(2) */
	3,	/* r512(3) */
	4	/* r768(4) */
};
static asn_INTEGER_specifics_t asn_SPC_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_specs_102 = {
	asn_MAP_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_value2enum_102,	/* "tag" => N; sorted by tag */
	asn_MAP_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_enum2value_102,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_tags_102[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102 = {
	"pdsch-maxNumRepetitionCEmodeB-SC-MTCH-r14",
	"pdsch-maxNumRepetitionCEmodeB-SC-MTCH-r14",
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_free,
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_print,
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_constraint,
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_decode_ber,
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_encode_der,
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_decode_xer,
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_encode_xer,
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_decode_uper,
	pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_tags_102,
	sizeof(asn_DEF_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_tags_102)
		/sizeof(asn_DEF_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_tags_102[0]) - 1, /* 1 */
	asn_DEF_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_tags_102,	/* Same as above */
	sizeof(asn_DEF_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_tags_102)
		/sizeof(asn_DEF_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_tags_102[0]), /* 2 */
	&asn_PER_type_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_constr_102,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_specs_102	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SystemInformationBlockType20_r13_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13, sc_mcch_RepetitionPeriod_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sc_mcch_RepetitionPeriod_r13_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sc-mcch-RepetitionPeriod-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13, sc_mcch_Offset_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_sc_mcch_Offset_r13_constraint_1,
		&asn_PER_memb_sc_mcch_Offset_r13_constr_11,
		0,
		"sc-mcch-Offset-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13, sc_mcch_FirstSubframe_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_sc_mcch_FirstSubframe_r13_constraint_1,
		&asn_PER_memb_sc_mcch_FirstSubframe_r13_constr_12,
		0,
		"sc-mcch-FirstSubframe-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct SystemInformationBlockType20_r13, sc_mcch_duration_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_sc_mcch_duration_r13_constraint_1,
		&asn_PER_memb_sc_mcch_duration_r13_constr_13,
		0,
		"sc-mcch-duration-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SystemInformationBlockType20_r13, sc_mcch_ModificationPeriod_r13),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sc_mcch_ModificationPeriod_r13_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sc-mcch-ModificationPeriod-r13"
		},
	{ ATF_POINTER, 5, offsetof(struct SystemInformationBlockType20_r13, lateNonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"lateNonCriticalExtension"
		},
	{ ATF_POINTER, 4, offsetof(struct SystemInformationBlockType20_r13, br_BCCH_Config_r14),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_br_BCCH_Config_r14_33,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"br-BCCH-Config-r14"
		},
	{ ATF_POINTER, 3, offsetof(struct SystemInformationBlockType20_r13, sc_mcch_SchedulingInfo_r14),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SC_MCCH_SchedulingInfo_r14,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sc-mcch-SchedulingInfo-r14"
		},
	{ ATF_POINTER, 2, offsetof(struct SystemInformationBlockType20_r13, pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_pdsch_maxNumRepetitionCEmodeA_SC_MTCH_r14_99,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"pdsch-maxNumRepetitionCEmodeA-SC-MTCH-r14"
		},
	{ ATF_POINTER, 1, offsetof(struct SystemInformationBlockType20_r13, pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_pdsch_maxNumRepetitionCEmodeB_SC_MTCH_r14_102,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"pdsch-maxNumRepetitionCEmodeB-SC-MTCH-r14"
		},
};
static int asn_MAP_SystemInformationBlockType20_r13_oms_1[] = { 3, 5, 6, 7, 8, 9 };
static ber_tlv_tag_t asn_DEF_SystemInformationBlockType20_r13_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SystemInformationBlockType20_r13_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sc-mcch-RepetitionPeriod-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sc-mcch-Offset-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sc-mcch-FirstSubframe-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sc-mcch-duration-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* sc-mcch-ModificationPeriod-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* lateNonCriticalExtension */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* br-BCCH-Config-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* sc-mcch-SchedulingInfo-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* pdsch-maxNumRepetitionCEmodeA-SC-MTCH-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* pdsch-maxNumRepetitionCEmodeB-SC-MTCH-r14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SystemInformationBlockType20_r13_specs_1 = {
	sizeof(struct SystemInformationBlockType20_r13),
	offsetof(struct SystemInformationBlockType20_r13, _asn_ctx),
	asn_MAP_SystemInformationBlockType20_r13_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_SystemInformationBlockType20_r13_oms_1,	/* Optional members */
	2, 4,	/* Root/Additions */
	5,	/* Start extensions */
	11	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType20_r13 = {
	"SystemInformationBlockType20-r13",
	"SystemInformationBlockType20-r13",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SystemInformationBlockType20_r13_tags_1,
	sizeof(asn_DEF_SystemInformationBlockType20_r13_tags_1)
		/sizeof(asn_DEF_SystemInformationBlockType20_r13_tags_1[0]), /* 1 */
	asn_DEF_SystemInformationBlockType20_r13_tags_1,	/* Same as above */
	sizeof(asn_DEF_SystemInformationBlockType20_r13_tags_1)
		/sizeof(asn_DEF_SystemInformationBlockType20_r13_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SystemInformationBlockType20_r13_1,
	10,	/* Elements count */
	&asn_SPC_SystemInformationBlockType20_r13_specs_1	/* Additional specs */
};

