/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-InterNodeDefinitions"
 * 	found in "36331-e30.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_UEPagingCoverageInformation_NB_IEs_H_
#define	_UEPagingCoverageInformation_NB_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UEPagingCoverageInformation-NB-IEs */
typedef struct UEPagingCoverageInformation_NB_IEs {
	long	*npdcch_NumRepetitionPaging_r13	/* OPTIONAL */;
	struct UEPagingCoverageInformation_NB_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEPagingCoverageInformation_NB_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEPagingCoverageInformation_NB_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _UEPagingCoverageInformation_NB_IEs_H_ */
#include <asn_internal.h>
